// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgresql://neondb_owner:npg_CpeBtgI64Uyv@ep-odd-bar-azn79xd0.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"] || process.env["postgresql://neondb_owner:npg_CpeBtgI64Uyv@ep-odd-bar-azn79xd0-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"],
  },
});
